# Generated by Django 4.2.2 on 2023-06-19 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('AId', models.AutoField(primary_key=True, serialize=False)),
                ('AF_Name', models.CharField(max_length=40)),
                ('AL_Name', models.CharField(max_length=30)),
                ('AAddress', models.CharField(max_length=40)),
                ('AMobilePhone', models.IntegerField(default=False)),
                ('AEmail', models.CharField(max_length=40)),
                ('ABirth_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('JId', models.AutoField(primary_key=True, serialize=False)),
                ('JName', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='AppJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobapp.applicant')),
                ('JID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobapp.job')),
            ],
        ),
    ]
