# Generated by Django 4.2.2 on 2023-06-22 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('AId', models.AutoField(primary_key=True, serialize=False)),
                ('AFName', models.CharField(max_length=40)),
                ('ALName', models.CharField(max_length=30)),
                ('Address', models.CharField(max_length=40)),
                ('AMobilePhone', models.IntegerField(default=False)),
                ('AEmail', models.CharField(max_length=40)),
                ('ABirth_date', models.DateField()),
            ],
            options={
                'db_table': 'applicant',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('JId', models.AutoField(primary_key=True, serialize=False)),
                ('JName', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'job',
            },
        ),
        migrations.CreateModel(
            name='Apps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Aid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobapp.applicant')),
                ('JId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobapp.job')),
            ],
            options={
                'db_table': 'apps',
            },
        ),
    ]
