# Generated by Django 4.2.2 on 2023-07-03 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicant',
            old_name='AId',
            new_name='Aid',
        ),
    ]
