# Generated by Django 4.2.2 on 2023-06-19 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='appjob',
            table='appjob',
        ),
        migrations.AlterModelTable(
            name='applicant',
            table='applicant',
        ),
        migrations.AlterModelTable(
            name='job',
            table='job',
        ),
    ]
