# Generated by Django 4.2.2 on 2023-07-04 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0002_rename_aid_applicant_aid'),
    ]

    operations = [
        migrations.AddField(
            model_name='apps',
            name='email',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apps',
            name='name',
            field=models.CharField(default=2012, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apps',
            name='skill',
            field=models.CharField(default=2012, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apps',
            name='wadhamin',
            field=models.CharField(default='04-03-2023', max_length=50),
            preserve_default=False,
        ),
    ]
