# Generated by Django 4.2.2 on 2023-07-04 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0003_apps_email_apps_name_apps_skill_apps_wadhamin'),
    ]

    operations = [
        migrations.AddField(
            model_name='apps',
            name='document',
            field=models.FileField(default='04-03-2023', upload_to='certificates/'),
            preserve_default=False,
        ),
    ]
