# Generated by Django 4.2.2 on 2023-07-05 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0004_apps_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apps',
            name='document',
        ),
    ]
